name: site gen

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repos!
        uses: actions/checkout@v2 
      - name: setup python environment!
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 
      - name: install dependencies!
        run: |
          python -m pip install --upgrade pip
          pip install gcn-kafka
          pip install numpy jinja2
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute the sitgen make cmd
        run: |
          make website
      - name: configure git identity [robot]
        run: |
          git config user.name  'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: commit changes
        run: |
          git add -A
          git commit -m "weeeeeeeee [just the site]"
      - name: deploy to website
        shell: bash
        run: git push origin 
